# Site settings
title: Authentic Jazz Weekend 2018
email: sweetheartkorea@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Authentic Jazz Weekend 2018
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.authenticjazzweekend.com" # the base hostname & protocol for your site, e.g. http://example.com
suburi: "/2018"
logo: "/2018/img/poster1.jpg"
google_analytics: "UA-44532734-2"

#twitter_username:

#facebook
facebook:
  app_id: 132917764008803
  publisher: https://www.facebook.com/sweetheartswing
  admins: 1018232241
facebook_url: "https://www.facebook.com/events/1753882241577424"
github_username: authenticjazzweekend

# Build settings
markdown: kramdown
#theme: minima
ampdir: "/2018/_amp"
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - amp-jekyll
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-lunr-js-search
include:
  - _redirects
exclude:
  - Gemfile
  - Gemfile.lock
timezone: Asia/Seoul
permalink: none

defaults:
  -
    scope:
      path: "_posts"
    values:
      skip_amp: "true"
      layout: "post"
      permalink: "2018/post/:categories/:title.html"
      image: "/2018/img/poster2.jpg"

carousel:
  - "/2018/img/cr0.jpg"
  - "/2018/img/cr1.jpg"
  - "/2018/img/cr2.jpg"
  - "/2018/img/cr3.jpg"

#seo
logo: "/2018/img/poster2.png"
google_site_verification: ""
webmaster_verifications:
  google: 1234
